class aix_usersec::params {
  $maxage       = ''
  $minlen       = ''
  $loginretries = ''
  $histexpire   = ''
  $histsize     = ''
  $minage       = ''
  $mindigit     = ''
  $maxexpired   = ''
  $minalpha     = ''
  $minother     = ''
  $mindiff      = ''
  $maxrepeats   = ''
  $umask        = ''
}
